import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';

export default function Dashboard(){
 const user=JSON.parse(localStorage.getItem('user')||'null'); const [stats,setStats]=useState({bookmarks:0,attempts:0}); const [careers,setCareers]=useState([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{try{const [b,q,c]=await Promise.all([api.get('/bookmarks'),api.get('/quiz/history'),api.get('/careers')]);if(alive){setStats({bookmarks:b.data.length||0,attempts:q.data.length||0});setCareers((c.data||[]).slice(0,3));}}catch(e){}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 return <main className="dashboard"><div className="dash-head"><div><span className="eyebrow">CAREER PASSPORT</span><h1>Good morning, {user?.name?.split(' ')[0]||'there'} 👋</h1><p className="muted">Explore your next opportunity and keep building your career path.</p></div><Link className="btn" to="/quiz">Take Career Quiz →</Link></div><section className="stats-grid"><div className="stat-card"><span>Quiz attempts</span><strong>{loading?'—':stats.attempts}</strong><small>Track your progress</small></div><div className="stat-card"><span>Saved items</span><strong>{loading?'—':stats.bookmarks}</strong><small>Your career shortlist</small></div><div className="stat-card"><span>Profile status</span><strong>Basic</strong><small><Link to="/profile">Complete profile →</Link></small></div></section><section className="quick-grid"><Link to="/careers" className="feature-card"><span className="icon">⌕</span><div><h3>Explore Career Bank</h3><p>Search roles, skills, salary and job demand.</p></div><b>→</b></Link><Link to="/quiz" className="feature-card"><span className="icon">✦</span><div><h3>Find Your Match</h3><p>Take the interest quiz and discover suitable paths.</p></div><b>→</b></Link><Link to="/resources" className="feature-card"><span className="icon">▣</span><div><h3>Learn & Prepare</h3><p>Browse career guides and learning resources.</p></div><b>→</b></Link></section><section className="section-head"><div><span className="eyebrow">TRENDING</span><h2>Careers to explore</h2></div><Link to="/careers">View all →</Link></section><div className="career-mini-grid">{careers.map(c=><Link className="career-mini" to={`/careers/${c._id}`} key={c._id}><span>{(c.title||'Career').slice(0,1)}</span><div><h3>{c.title}</h3><p>{c.domain||'Career'} · {c.demand||'Growing demand'}</p></div><b>→</b></Link>)}{!careers.length&&!loading&&<div className="empty">No careers have been added yet. An admin can add them from the Admin panel.</div>}</div></main>
}
