import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api } from '../services/api';

export default function Register(){
 const navigate=useNavigate(); const [form,setForm]=useState({name:'',email:'',password:'',role:'student'}); const [confirm,setConfirm]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const submit=async e=>{e.preventDefault();setError('');if(form.password!==confirm)return setError('Passwords do not match.');setLoading(true);try{const {data}=await api.post('/auth/register',form);localStorage.setItem('token',data.token);localStorage.setItem('user',JSON.stringify(data.user));navigate('/dashboard')}catch(err){setError(err.response?.data?.message||'Unable to create account.')}finally{setLoading(false)}};
 return <main className="auth-page"><section className="auth-card register-card"><div className="auth-brand"><span>PS</span><div><strong>PathSeeker</strong><small>Career Passport</small></div></div><h1>Create your account</h1><p className="muted">Tell us a little about yourself to get personalized career guidance.</p>{error&&<div className="alert error">{error}</div>}<form onSubmit={submit}><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your full name"/></label><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><div className="two-col"><label>Password<input type="password" required minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Minimum 6 characters"/></label><label>Confirm password<input type="password" required value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat password"/></label></div><label>I'm a...<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="student">Student</option><option value="graduate">Graduate</option><option value="professional">Working Professional</option></select></label><button className="btn full" disabled={loading}>{loading?'Creating account...':'Create Account'}</button></form><p className="auth-bottom">Already have an account? <Link to="/login">Login</Link></p></section></main>
}
